### ISSUE TITLE
Image broken in web - using latest flutter version

### ISSUE THREAD

**Issue by ri3tykity** [MuhammadHassanRazaa/FlutterSocialLoginButtons#5]
![image](https://github.com/MuhammadHassanRazaa/FlutterSocialLoginButtons/assets/9484973/60a5236d-f844-4618-932e-85c6f94293a5)
This is the UI result
Step to reproduce: Install package and use as instructed in readme.md

**Comment by MuhammadHassanRazaa** [comment]
please use this version:

`social_login_buttons: 1.0.7`

**Comment by MuhammadHassanRazaa** [comment]
please use this version:

`social_login_buttons: 1.0.7`

![image](https://github.com/MuhammadHassanRazaa/FlutterSocialLoginButtons/assets/47544114/4afbb478-6c63-4ec9-90ad-7cdf81cac8ff)


Let me know if any issue after even with this verison
